version: '3.7'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=php-api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - user-network
    ports:
      - "3306:3306"

  php:
    build: ./.docker/php
    ports: ['9000:9000']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www/user-api']
    networks:
      - user-network

  nginx:
    build: ./.docker/nginx
    ports: ['80:80']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www/user-api']
    networks:
      - user-network

networks:
  user-network:
